trigger:
- main

pool:
  name: Self-Managed-Pool


steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "usman59228@gmail.com"
      git config --global user.name "musman3"
      git clone https://github.com/MadProgrammerHere/test-repo.git
      cd test-repo
      git branch
      # Modify files here
      touch file2.txt
      git add .
      git commit -m "Added file"
      git push https://$(pat)@github.com/MadProgrammerHere/test-repo.git
